//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBlog.Website.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCBlog.Website.Properties.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue reading ....
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this comment?.
        /// </summary>
        public static string DeleteCommentConfirmation {
            get {
                return ResourceManager.GetString("DeleteCommentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this post?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. The webmaster was notified..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested page could not be found..
        /// </summary>
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorPingback {
            get {
                return ResourceManager.GetString("ErrorPingback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to write and edit blog posts. The default login and password is &apos;admin&apos;. You can change this in web.config!.
        /// </summary>
        public static string HeroText {
            get {
                return ResourceManager.GetString("HeroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML-Code.
        /// </summary>
        public static string HTMLCode {
            get {
                return ResourceManager.GetString("HTMLCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML-Code (Lightbox).
        /// </summary>
        public static string HTMLCodeLightbox {
            get {
                return ResourceManager.GetString("HTMLCodeLightbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Management.
        /// </summary>
        public static string ImagesManagement {
            get {
                return ResourceManager.GetString("ImagesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        public static string Imprint {
            get {
                return ResourceManager.GetString("Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start page.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load/Unload editor.
        /// </summary>
        public static string LoadEditor {
            get {
                return ResourceManager.GetString("LoadEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metainformation.
        /// </summary>
        public static string MetaData {
            get {
                return ResourceManager.GetString("MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New post.
        /// </summary>
        public static string NewBlogEntry {
            get {
                return ResourceManager.GetString("NewBlogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New comment.
        /// </summary>
        public static string NewComment {
            get {
                return ResourceManager.GetString("NewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments available..
        /// </summary>
        public static string NoComments {
            get {
                return ResourceManager.GetString("NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries available..
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform pingbacks.
        /// </summary>
        public static string PerformPingbacks {
            get {
                return ResourceManager.GetString("PerformPingbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pingback only possible, if entry is publically visible.
        /// </summary>
        public static string PingbackOnlyWhenVisible {
            get {
                return ResourceManager.GetString("PingbackOnlyWhenVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pingbacks.
        /// </summary>
        public static string Pingbacks {
            get {
                return ResourceManager.GetString("Pingbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Posts.
        /// </summary>
        public static string PopularPosts {
            get {
                return ResourceManager.GetString("PopularPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related posts.
        /// </summary>
        public static string RelatedPosts {
            get {
                return ResourceManager.GetString("RelatedPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining number of characters.
        /// </summary>
        public static string RemainingChars {
            get {
                return ResourceManager.GetString("RemainingChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save login.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to RSS Feed.
        /// </summary>
        public static string RssFeed {
            get {
                return ResourceManager.GetString("RssFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS Readers.
        /// </summary>
        public static string RSSReaders {
            get {
                return ResourceManager.GetString("RSSReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show post.
        /// </summary>
        public static string ShowPost {
            get {
                return ResourceManager.GetString("ShowPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Users.
        /// </summary>
        public static string SingleUsers {
            get {
                return ResourceManager.GetString("SingleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show comments.
        /// </summary>
        public static string ToComments {
            get {
                return ResourceManager.GetString("ToComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        public static string Visits {
            get {
                return ResourceManager.GetString("Visits", resourceCulture);
            }
        }
    }
}
