// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _LogonControl = "_LogonControl";
                public readonly string _PopularBlogEntriesControl = "_PopularBlogEntriesControl";
                public readonly string _TagListControl = "_TagListControl";
                public readonly string Error = "Error";
                public readonly string NotFound = "NotFound";
                public readonly string Sidebar_Layout = "Sidebar.Layout";
                public readonly string Site_Layout = "Site.Layout";
            }
            public readonly string _LogonControl = "~/Views/Shared/_LogonControl.cshtml";
            public readonly string _PopularBlogEntriesControl = "~/Views/Shared/_PopularBlogEntriesControl.cshtml";
            public readonly string _TagListControl = "~/Views/Shared/_TagListControl.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string NotFound = "~/Views/Shared/NotFound.cshtml";
            public readonly string Sidebar_Layout = "~/Views/Shared/Sidebar.Layout.cshtml";
            public readonly string Site_Layout = "~/Views/Shared/Site.Layout.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string CanonicalHelperModel = "CanonicalHelperModel";
                public readonly string MenuHelperModel = "MenuHelperModel";
                public readonly string MetaRobotsHelperModel = "MetaRobotsHelperModel";
                public readonly string SiteMapHelperModel = "SiteMapHelperModel";
                public readonly string SiteMapNodeModel = "SiteMapNodeModel";
                public readonly string SiteMapNodeModelList = "SiteMapNodeModelList";
                public readonly string SiteMapPathHelperModel = "SiteMapPathHelperModel";
                public readonly string SiteMapTitleHelperModel = "SiteMapTitleHelperModel";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
