rmdir /s/q MVCBlog.Business.Test\TestResults

mkdir TestResults
mkdir TestResults\reports

dotnet test --collect:"XPlat Code Coverage"

"%UserProfile%\.nuget\packages\reportgenerator\5.1.19\tools\net7.0\ReportGenerator.exe" -reports:MVCBlog.*.Test\TestResults\*\coverage.cobertura.xml -reporttypes:Html;TeamCitySummary -targetdir:TestResults\reports -verbosity:Info -historydir:TestResults\reports\history -classfilters:-AutoGeneratedProgram;-MVCBlog.Data.Migrations*;